# Generated by Django 2.0.3 on 2018-07-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macaca', '0002_auto_20180716_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='code',
            field=models.CharField(default='', help_text='species code', max_length=10),
            preserve_default=False,
        ),
    ]
