# Generated by Django 2.1.7 on 2019-12-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macaca', '0003_species_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_type',
            field=models.CharField(help_text='drugbank drug type', max_length=20),
        ),
        migrations.AlterField(
            model_name='gene',
            name='biotype',
            field=models.CharField(help_text='gene coding type', max_length=30),
        ),
    ]
