# Generated by Django 2.1.7 on 2019-12-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macaca', '0004_auto_20191219_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='inheritance',
            field=models.CharField(help_text='Inheritance', max_length=80),
        ),
    ]
