# Generated by Django 2.0 on 2017-12-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snpdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geneannot',
            old_name='gene_id',
            new_name='gene',
        ),
        migrations.RenameField(
            model_name='geneannot',
            old_name='snp_id',
            new_name='snp',
        ),
        migrations.RenameField(
            model_name='snp',
            old_name='chr_id',
            new_name='chrom',
        ),
        migrations.RenameField(
            model_name='transannot',
            old_name='snp_id',
            new_name='snp',
        ),
        migrations.RenameField(
            model_name='transannot',
            old_name='trans_id',
            new_name='transcript',
        ),
        migrations.RenameField(
            model_name='transannot',
            old_name='trans_pos',
            new_name='transcript_pos',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='snp_id',
            new_name='snp',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='species_id',
            new_name='species',
        ),
    ]
